config/routes.rb
Realestate::Application.routes.draw do
  
  devise_for :admins

  devise_for :builders
 

  resources :dashboards do
    collection do
      get 'search'
    end
  end
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :builderregistrations
  resources :profiles 
  
    
   
  namespace :admin do
    resources :users
    resources :builders do
      member do
        get :block_builders
        get :manage_properties
      end
    end
  end

  devise_scope :user do
    get "sign_out", :to => "sessions#destroy"
  end
  
  

  resources :images
  
  resources :builders do
    resources :properties do
      member do
        get :manage_property
        get 'summary'
      end
    end
  end
  
  resources :properties do
  member do
    get 'add_contact'
    post 'post_contact'
    get 'reply_user'
  end
end
  
  
  
  

root :to => 'dashboards#index'

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :builder_id,:property_name,:property_listing,:property_type,:no_of_flats,:no_of_floors,:images_attributes,:no_of_houses,:no_of_plots,:state,:city,:address,:zip_code,:latitude,:longitude,:total_area,:saleable_area,:sale_price,:parking,:swimming,:playground,:party_hall,:property_status,:start_date,:end_date,:upcoming_date,:description, :gmaps,:published,:expire_date,:search_view,:full_view
  validates :builder_id, :property_name, :property_listing, :property_type,:property_status, :total_area,:saleable_area,:sale_price,:presence => true
  
  belongs_to :builder  
  has_many :images 
  has_many :contacts
  
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
  
  validates_format_of :zip_code,
                  :with => /\A\{6}-\d{5}|\A\d{6}\z/,
                  :message => "should be 123456 or 12345-1234",
                  :allow_blank => false
                
  acts_as_gmappable 

  def gmaps4rails_address
  "#{self.address}, #{self.city}, #{self.zip_code}" 
  end

  scope :property_listing, lambda { |*args|
    unless args.first.blank?
      {:conditions => ["property_listing = ?", args.first]}
    end
  }
  
  scope :property_type, lambda { |*args|
    unless args.first.blank?
      {:conditions => ["property_type = ?", args.first]}
    end
  }
  
  scope :sale_price, lambda { |*args|
    unless args.first.blank?
      {:conditions => ["sale_price = ?", args.first]}
    end
  }
  
  scope :city, lambda { |*args|
    unless args.first.blank?
      {:conditions => ["city = ?", args.first]}
    end
  }
  
  def gmaps4rails_infowindow
    "Address: #{self.address} <br/> City: #{self.city} <br /> Longitude: #{self.longitude} <br/> Latitude: #{self.latitude}"
  end
    
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_filter :allow_builder, :only => [ "edit",  "destroy"]
  
  def allow_builder
    @property = Property.find(params[:id])
    unless @property.builder_id==current_builder.id
      flash[:notice]="Access Denied"
      redirect_to properties_path
    end
  end 

  def index
    if params[:format].present?
      @builder = Builder.find_by_id(params[:format])
      @properties = @builder.properties
    else
      @properties = current_builder.properties.where("published = #{true}")
    end
  end
  
  def show
    @property = Property.find(params[:id])
    @property.update_attributes(:full_view =>@property.full_view+1)
    @json = @property.to_gmaps4rails
    @contact = Contact.new
  end

  def new
    @builder = params[:builder_id] ? Builder.find(params[:builder_id]) : current_builder
    @property = Property.new
    1.times {@property.images.build}
  end
  
  def create
    @builder = params[:builder_id] ? Builder.find(params[:builder_id]) : current_builder
    @property = Property.new(params[:property])
    @property.builder_id = @builder.id
      
    if @property.images.blank?
      1.times {@property.images.build}
    end
    
    if params[:property][:property_type]=='Apartment'
      @property.no_of_houses=""
      @property.no_of_plots=""
    elsif params[:property][:property_type]=='Villa'
      @property.no_of_flats=""
      @property.no_of_plots=""
    elsif params[:property][:property_type]=='Row House'
      @property.no_of_flats=""
      @property.no_of_plots=""
    elsif params[:property][:property_type]=='Layout'
      @property.no_of_houses=""
      @property.no_of_flats=""
      @property.no_of_floors=""
    end
    
    if params[:property][:property_status]=='Ready To Move'
      @property.start_date=""
      @property.upcoming_date=""
    elsif params[:property][:property_status]=='Ongoing'
      @property.upcoming_date="" 
    elsif params[:property][:property_status]=='Upcoming'
      @property.start_date=""
      @property.end_date=""
    end
    
    if @property.save
      @property.update_attribute(:published, false)
      flash[:notice]="property created successfully"
      redirect_to '/'
    else
      flash[:error] = "property creation failed"
      render 'new'
    end
  end
  
  def edit
    @builder = Builder.find params[:builder_id]
    @property = Property.find(params[:id])
  end
  
  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(params[:property])
      redirect_to properties_path
    else
      #@property.errors.inspect
      render :action => :edit
    end
  end
  
  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to properties_path
  end
  
  def manage_property
    @properties = Property.find params[:id]
    @properties.update_attribute(:published,params[:status])
    redirect_to manage_properties_admin_builder_path(@properties.builder)
  end

  def add_contact
    @contact = Contact.new
  end
  
  def post_contact
    @property = Property.find(params[:id])
    @title = "Contact"
    @contact = Contact.new(params[:contact].merge(:property_id => @property.id))
    @contact.builder_id = @property.builder_id
    if @contact.save
      ContactMailer.enquiry(@contact, @property).deliver
      redirect_to property_path(@property)
    else
      render :action => 'show'
    end
  end

  def summary
    @property = Property.find(params[:id])
  end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_contact.html.erb
<%= form_for @contact, :url => post_contact_property_path(@property, @contact), :html => {:method => 'post'} do |f| %>
  <div class="row-fluid">
    <div class="span6 well">
      <h5>Request More Info</h5>
      <div class="row-fluid">
        <div class="row-fluid">
          <div class="span12">
            <p>I would like to:</p>
            <div class="row-fluid">              
              <div class="span4">
                <%= f.radio_button :contact_option, "1", :checked => true %>
                <span>Make an enquiry</span>
              </div>
            </div>
            <div class="row-fluid">
              <div class="span6">
                <%= f.radio_button :contact_option, "2"%>
                <span>Request an appointment</span>
              </div>
            </div>
            <div class="row-fluid">
              <div class="span6">
                <%= f.radio_button :contact_option, "3"%>
                <span>Inquire if this property is still available</span>
              </div>
            </div>
          </div>
        </div>

        <div id="basic_info">
          <div class="row-fluid">
            <div class="span4">Name:</div>
            <div class="span4"><%= f.text_field :name %></div>
          </div>
          <div class="row-fluid">
            <div class="span4">Email:</div>
            <div class="span4"><%= f.text_field :email %></div>
          </div>
          <div class="row-fluid">
            <div class="span4">Phone:</div>
            <div class="span4"><%= f.text_field :phone %></div>
          </div>
        </div>
        
        <div id="qry">
          <div class="row-fluid">
            <div class="span6">What would you like to ask?</div>
          </div>
          <div>
            <%= f.text_area :question, :rows => 3, :cols => 60 %>
          </div>
        </div>
        <div id="date_time">
          <div class="row-fluid">
            <div class="span6">When are you free?</div>
          </div>
          <div class="row-fluid">
            <div class="span6">
              <div id="datetimepicker1" class="input-append date">
                <style>
                  .btn{
                    padding :0;
                  }
                </style>
                <%= f.text_field :appointment_time, "data-format"=>"dd/MM/yyyy hh:mm:ss" %>
                <span class="add-on">
                  <i data-time-icon="icon-time" data-date-icon="icon-calendar">
                  </i>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div>
          <%= f.submit "Send Message" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<style>
  #contact_question{
    width: 364px;
  }
</style>

<script type="text/javascript">
  $(document).ready(function() {
    $('#date_time').hide();
    $('#basic_info').show();
    $('#qry').show();
    $('#contact_contact_option_3').live("click", function() {
        $('#date_time').hide();
        $('#basic_info').show();
        $('#qry').hide();
    })

    $('#contact_contact_option_1').live("click", function() {
      $('#date_time').hide();
      $('#basic_info').show();
      $('#qry').show();
    })
    
    $('#contact_contact_option_2').live("click", function() {
      $('#date_time').show();
      $('#basic_info').show();
      $('#qry').show();
    })
  });

  $(function() {
    $('#datetimepicker1').datetimepicker({
      format: 'dd/MM/yyyy hh:mm:ss',
      language: 'en'
    });
  });
</script>

app/views/properties/_form.html.erb
  <% if !@property.errors.empty? %>
    <ul>
      <% @property.errors.each do |attr,message| %>
        <li><%= attr %>&nbsp;<%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div id="property_descr">
    <div>
      <span style="margin-right: 30px;">Property Name:</span>
      <span><%= f.text_field :property_name %></span>
    </div>

    <div>
      <span style="margin-right: 28px;">Property Listing:</span>
      <span><%=f.select :property_listing, options_for_select(["For Sale","For Rent","For Sale or Rent"]) %></span>
    </div>

    <div>
      <span style="margin-right: 37px;">Property Type:</span>
      <span><%=f.select :property_type, options_for_select([["Select" ,""],["Apartment","Apartment"],["Villa","Villa"],["Row House","Row House"],["Layout","Layout"]],:selected => f.object.property_type) %></span>
    </div>

    <div id="flats">
      <span style="margin-right: 62px;">No of flats:</span>
      <span><%=f.select :no_of_flats, options_for_select(["1BHK","2BHK","3BHK","4BHK","5BHK","6BHK","7BHK","8BHK"]) %></span>
    </div>

    <div id="floors">
      <span style="margin-right: 53px;">No of floors:</span>
      <span><%=f.select :no_of_floors, options_for_select(1..50) %></span>
    </div>

    <div id="houses">
      <span style="margin-right: 40px;">No of Houses:</span>
      <span><%=f.select :no_of_houses, options_for_select(1..50) %></span>
    </div>

    <div id="plots">
      <span style="margin-right: 57px;">No of Plots:</span>
      <span><%=f.select :no_of_plots, options_for_select(1..50) %></span>
    </div>

    <div>
      <span style="margin-right: 25px;">Total Area(SQF):</span>
      <span><%=f.text_field :total_area %></span>
    </div>

    <div>
      <span style="margin-right: 05px;">SaleableArea(SQF):</span>
      <span><%=f.text_field :saleable_area %></span>
    </div>

    <div>
      <span style="margin-right: 62px;">Sale Price:</span>
      <span><%=f.text_field :sale_price %></span>
    </div>

    <div>
      <span style="margin-right: 55px;">Description:</span>
      <span><%=f.text_area :description, :rows => 2, :cols => 5 %></span>
    </div>

    <div style="margin-bottom: 14px;">
      <span style="margin-right: 24px;">Remaining Area:</span>
      <span><%= f.check_box :parking %>Parking</span>
      <span style="margin-left: 70px;"><%= f.check_box :swimming %>Swimming</span><br/>
      <span style="margin-left: 134px"><%= f.check_box :playground %>Playground</span>
      <span style="margin-left: 47px;"><%= f.check_box :party_hall %>Party hall</span>
    </div>
  </div>  

  <div id="body_property">
    <div>
      <span style="margin-right: 25px;">Property Status:</span>
      <span><%=f.select :property_status,options_for_select([["Select",""],['Ongoing',"Ongoing"],['Ready To Move','Ready To Move'],['Upcoming','Upcoming']], :selected => f.object.property_status) %></span>
    </div>

    <div id="start">
      <span style="margin-right: 60px;">Project Start Date:</span>
      <span><%=f.date_select :start_date %></span>
    </div>

    <div id="end">
      <span style="margin-right: 19px;">Project Completion Date:</span>
      <span><%=f.date_select :end_date %></span>
    </div>

    <div id="upcoming">
      <span style="margin-right: 25px;">Project Upcoming Date:</span>
      <span><%=f.date_select :upcoming_date %></span>
    </div>
  </div>

  <div id="img">
    <h4>Upload Images For Your Properties</h4>
    <div style="margin-bottom: 20px;">
      <%= f.fields_for :images, :html => {:multipart => true} do |builder| %>
        <%= builder.file_field :image %>
      <% end %>  
      <br/>
      <div style="margin: 10px 0px">
        <%= link_to_add_fields "Upload More Images", f,:images %> 
      </div>
    </div>       
  </div>

  <div id="body_addr">
    
    <div>
      <span style="margin-right: 92px;">State:</span>
      <span><%=f.text_field :state %></span>
    </div>

    <div>
      <span style="margin-right: 102px;">City:</span>
      <span><%=f.text_field :city %></span>
    </div>

    <div>
      <span style="margin-right: 74px;">Address:</span>
      <span><%=f.text_area :address,:rows => 2, :cols => 4 %></span>
    </div>

    <div>
      <span style="margin-right: 49px;">Postal Code:</span>
      <span><%=f.text_field :zip_code %></span>
    </div>


  </div>


    <div id="submit" style="margin: 40px 0px">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>


<span id="ns" style="margin-right: 20px;">
  <%= link_to_function image_tag('nt.jpg'), "steps();" %>
</span>

<span id="nt" style="margin-right: 20px;">
  <%= link_to_function image_tag('nt.jpg'), "stept();" %>
</span>

<span id="nf" style="margin-right: 20px;">
  <%= link_to_function image_tag('nt.jpg'), "stepf();" %>
</span>

<span id="bf">
  <%= link_to_function image_tag('bk.jpg'), "step1();" %>
</span>

<span id="bs">
  <%= link_to_function image_tag('bk.jpg'), "steps();" %>
</span>

<span id="bt">
  <%= link_to_function image_tag('bk.jpg'), "stept();" %>
</span>

<script>
  $(document).ready(function() {
    $('#start').hide();
    $('#end').hide();
    $('#upcoming').hide();

    $('#property_property_status').live("change", function() {
      if ($('#property_property_status').val() == "Ongoing") {
        $('#start').show();
        $('#end').show();
        $('#upcoming').hide();
      }
      else if ($('#property_property_status').val() == "Ready To Move") {
        $('#start').hide();
        $('#end').show();
        $('#upcoming').hide();
      }
      else if ($('#property_property_status').val() == "Upcoming") {
        $('#start').hide();
        $('#end').hide();
        $('#upcoming').show();
      }
      else {
        $('#start').hide();
        $('#end').hide();
        $('#upcoming').hide();
      }
    })
  })

  $(document).ready(function() {
    $('#flats').hide();
    $('#floors').hide();
    $('#houses').hide();
    $('#plots').hide();

    $('#property_property_type').live("change", function() {
      if ($('#property_property_type').val() == "Apartment") {
        $('#flats').show();
        $('#floors').show();
        $('#houses').hide();
        $('#plots').hide();
      }
      else if ($('#property_property_type').val() == "Villa") {
        $('#flats').hide();
        $('#floors').show();
        $('#houses').show();
        $('#plots').hide();
      }
      else if ($('#property_property_type').val() == "Row House") {
        $('#flats').hide();
        $('#floors').show();
        $('#houses').show();
        $('#plots').hide();
      }
      else if ($('#property_property_type').val() == "Layout") {
        $('#flats').hide();
        $('#floors').hide();
        $('#houses').hide();
        $('#plots').show();
      }
      else {
        $('#flats').hide();
        $('#floors').hide();
        $('#houses').hide();
        $('#plots').hide();
      }
    })
  })

  $(document).ready(function() {
    $('#img').hide();
    $('#body_addr').hide();
    $('#property_descr').show();
    $('#body_property').show();
    $('#submit').hide();

    $('#step1').show();
    $('#step2').hide();
    $('#step3').hide();
    $('#step4').hide();

    $('#ns').show();
    $('#nt').hide();
    $('#nf').hide();

    $('#bf').hide();
    $('#bs').hide();
    $('#bt').hide();
  })
  
  function step1() {
    $('#img').hide();
    $('#body_addr').hide();
    $('#property_descr').show();
    $('#body_property').show();
    $('#submit').hide();

    $('#step1').show();
    $('#step2').hide();
    $('#step3').hide();
    $('#step4').hide();

    $('#ns').show();
    $('#nt').hide();
    $('#nf').hide();

    $('#bf').hide();
    $('#bs').hide();
    $('#bt').hide();
  }

  function steps() {
    $("#img").show();
    $("#body_addr").hide();
    $('#property_descr').hide();
    $('#body_property').hide();
    $('#submit').hide();

    $('#step1').hide();
    $('#step2').show();
    $('#step3').hide();
    $('#step4').hide();

    $('#ns').hide();
    $('#nt').show();
    $('#nf').hide();

    $('#bf').show();
    $('#bs').hide();
    $('#bt').hide();
  }

  function stept() {
    $("#img").hide();
    $("#body_addr").show();
    $('#property_descr').hide();
    $('#body_property').hide();
    $('#submit').hide();

    $('#step1').hide();
    $('#step2').hide();
    $('#step3').show();
    $('#step4').hide();

    $('#ns').hide();
    $('#nt').hide();
    $('#nf').show();

    $('#bf').hide();
    $('#bs').show();
    $('#bt').hide();
  }

  function stepf() {
    $("#img").hide();
    $("#body_addr").hide();
    $('#property_descr').hide();
    $('#body_property').hide();
    $('#submit').show();

    $('#step1').hide();
    $('#step2').hide();
    $('#step3').hide();
    $('#step4').show();

    $('#ns').hide();
    $('#nt').hide();
    $('#nf').hide();

    $('#bf').hide();
    $('#bs').hide();
    $('#bt').show();
  }
</script>

app/views/properties/_image_fields.html.erb
<div class="fields">
  <%= f.file_field :image %>
  <%= link_to_remove_fields image_tag("cross.png"), f %>
</div>

app/views/properties/_map.html.erb
<%= gmaps4rails(@json) %>

app/views/properties/edit.html.erb
<span>
  <span id="step1"><%=  "Step1" %></span>
  <span id="step2"><%=  "Step2" %></span>
  <span id="step3"><%=  "Step3" %></span>
  <span id="step4"><%=  "Step4" %></span>
</span>

<%= form_for @property,:url => builder_property_path(@builder,@property) do |f| %>
  <%= render :partial => 'properties/form', :locals => {:f => f}%>
<% end %>

app/views/properties/index.html.erb
<%=link_to "Add",new_property_path%>
<table class="table table-striped" cellspacing="10" cellpadding="10" border="1">
  <tr>
    <th>PropertyName</th>
    <th>PropertyListing</th>
    <th>PropertyType</th>
    <th>TotalArea</th>
    <th>SalePrice</th>
    <th>State</th>
    <th>City</th>
    <th>Address</th>
    <th>PropertyStatus</th>
    <th>StartDate</th>
    <th>EndDate</th>
    <th>UpcomingDate</th>
    <th>Actions</th>
  </tr>

  <% @properties.each do |property| %>
    <tr>
      <td align="center">
        <%= property.property_name %>
      </td>
      <td align="center">
        <%= property.property_listing %>
      </td>
      <td align="center">
        <%= property.property_type %>
      </td>
      <td align="center">
        <%= property.total_area %>
      </td>
      <td align="center">
        <%= property.sale_price %>
      </td>
      <td align="center">
        <%= property.state %>
      </td>
      <td align="center">
        <%= property.city %>
      </td>
      <td align="center">
        <%= property.address %>
      </td>
      <td align="center">
        <%= property.property_status %>
      </td>
      <td>  
        <% if property.property_status == "Ongoing"  %>

          <%=property.start_date %>

        <td>
          <%=property.end_date %>
        </td>

      <% end %>

      <% if property.property_status == "Ready To Move"  %>
        <td>
          <%=property.end_date %>
        </td>
      <% end %>

      <td> 
        <% if property.property_status == "Upcoming"  %>
        <td>
          <%=property.upcoming_date %>
        </td>
      <% end %>
      </td>
      </td>

      <td>
        <%= link_to "Edit",  edit_builder_property_path(property.builder_id,property) %> </br>
        <%= link_to "View",  builder_property_path(property.builder_id,property) %>
        <%= link_to "Summary",summary_builder_property_path(property.builder_id,property) %>
        <%= button_to "Delete", builder_property_path(property.builder_id,property), :confirm => 'Are u sure to delete?',:method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/properties/new.html.erb
<span>
  <span id="step1"><%=  "Step1" %></span>
  <span id="step2"><%=  "Step2" %></span>
  <span id="step3"><%=  "Step3" %></span>
  <span id="step4"><%=  "Step4" %></span>
</span>

<%= form_for @property,:url => builder_properties_path(@builder,@property) do |f| %>
  <%= render :partial => 'properties/form',:locals => {:f => f}%>
<% end %>

app/views/properties/show.html.erb
<div class="row-fluid">
  <div class="span12">
    <h2>Property Details</h2>
    <div class="row-fluid">
      <div class="span6">
        <h5>Property Information</h5>
        <div class="row-fluid">
          <div class="span4">Property Name :</div>
          <div class="span4"><%= @property.property_name %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Property Listing :</div>
          <div class="span4"><%= @property.property_listing %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Total Area(sq.ft) :</div>
          <div class="span4"><%= @property.total_area %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Sale Area(sq.ft) :</div>
          <div class="span4"><%= @property.saleable_area %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Sale Price(Rs) :</div>
          <div class="span4"><%= @property.sale_price %></div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <h5>Type of Property</h5>
        <div class="row-fluid">
          <div class="span4">Property Type:</div>
          <div class="span4"><%= @property.property_type %></div>
        </div>
        <% if @property.property_type=="Villa" || @property.property_type == "Row House" %>
          <div class="row-fluid">
            <div class="span4">Number of Floors:</div>
            <div class="span4"><%= @property.no_of_floors %></div>
          </div>
          <div class="row-fluid">
            <div class="span4">Number of Houses:</div>
            <div class="span4"><%= @property.no_of_houses %></div>
          </div>
        <% end %>
        <% if @property.property_type == "Apartment"  %>
          <div class="row-fluid">
            <div class="span4">Number of Flats:</div>
            <div class="span4"><%= @property.no_of_flats %></div>
          </div>
          <div class="row-fluid">
            <div class="span4">Number of Floors:</div>
            <div class="span4"><%= @property.no_of_floors %></div>
          </div>
        <% end %>
        <% if @property.property_type == "Layout"  %>
          <div class="row-fluid">
            <div class="span4">Number of Plots:</div>
            <div class="span4"><%= @property.no_of_plots %></div>
          </div>
        <% end %> 
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <h5>Images:</h5>
        <div class="row-fluid">
          <% @property.images.each do |image| %>
            <div class="span4">
              <%= image_tag (image.image),:width=>"150", :height=>"50" %>
            </div>
          <% end%> 
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <h5>Property Status</h5>
        <div class="row-fluid">
          <div class="span4">Status:</div>
          <div class="span4"><%= @property.property_status %></div>
        </div>
        <% if @property.property_status == "Ongoing"  %>
          <div class="row-fluid">
            <div class="span4">Start Date:</div>
            <div class="span4"><%= @property.start_date %></div>
          </div>
          <div class="row-fluid">
            <div class="span4">Completion Date:</div>
            <div class="span4"><%= @property.end_date %></div>
          </div>
        <% end %>
        <% if @property.property_status == "Ready To Move"  %>
          <div class="row-fluid">
            <div class="span4">Completion Date:</div>
            <div class="span4"><%= @property.end_date %></div>
          </div>
        <% end %>
        <% if @property.property_status == "Upcoming"  %>
          <div class="row-fluid">
            <div class="span4">Upcoming Date:</div>
            <div class="span4"><%= @property.upcoming_date %></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <h5>Additional Features</h5>
        <% if @property.parking == 1 %>
          <div class="row-fluid">
            <div class="span4">Parking:</div>
            <div class="span4">available</div>
          </div>
        <% end %>
        <% if  @property.swimming == 1 %>
          <div class="row-fluid">
            <div class="span4">Swimming:</div>
            <div class="span4">available</div>
          </div>
        <% end %>
        <% if  @property.playground == 1 %>
          <div class="row-fluid">
            <div class="span4">Playground:</div>
            <div class="span4">available</div>
          </div>
        <% end %>
        <% if @property.party_hall == 1 %>
          <div class="row-fluid">
            <div class="span4">Party Hall:</div>
            <div class="span4">available</div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <h5>Property Location</h5>
        <div class="row-fluid">
          <div class="span4">State:</div>
          <div class="span4"><%= @property.state %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">City:</div>
          <div class="span4"><%= @property.city %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Address:</div>
          <div class="span4"><%= @property.address %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Postal Code</div>
          <div class="span4"><%= @property.zip_code %></div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <h5>Property on Map</h5>
        <div class="row-fluid">
          <div class="span12"><%= render 'map' %></div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <h5>Property Description</h5>
        <div class="row-fluid">
          <div class="span12"><%= @property.description %></div>
        </div>
      </div>
    </div>


    <div class="row-fluid">
      <div class="span6">
        <h5>Builder Information:</h5>
        <div class="row-fluid">
          <div class="span4">Builder:</div>
          <div class="span4"><%= @property.builder.company_name %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Logo:</div>
          <div class="span4"><%= image_tag (@property.builder.logo), :class => 'img-circle' %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Website Address:</div>
          <div class="span4"><%= link_to @property.builder.company_url, @property.builder.company_url %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Email:</div>
          <div class="span4"><%= @property.builder.email %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Phone:</div>
          <div class="span4"><%= @property.builder.phone %></div>
        </div>
        <div class="row-fluid">
          <div class="span4">Location:</div>
          <div class="span4"><%= @property.builder.city %></div>
        </div>
      </div>
    </div>
    <%if !current_builder %>
      <%= render 'contact' %>
    <% end %>
  </div>
</div>