config/routes.rb
Realestate::Application.routes.draw do
  
  devise_for :admins

  devise_for :builders
 

  resources :dashboards do
    collection do
      get 'search'
    end
  end
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :builderregistrations
  resources :profiles 
  
    
   
  namespace :admin do
    resources :users
    resources :builders do
      member do
        get :block_builders
        get :manage_properties
      end
    end
  end

  devise_scope :user do
    get "sign_out", :to => "sessions#destroy"
  end
  
  

  resources :images
  
  resources :builders do
    resources :properties do
      member do
        get :manage_property
        get 'summary'
      end
    end
  end
  
  resources :properties do
  member do
    get 'add_contact'
    post 'post_contact'
    get 'reply_user'
  end
end
  
  
  
  

root :to => 'dashboards#index'

end

app/models/builder.rb
class Builder < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :email,:password, :password_confirmation, :remember_me, :confirmation_token, :confirmed_at, :confirmation_sent_at, :unconfirmed_email,:first_name, :last_name, :company_name, :phone, :country, :address, :city, :logo, :company_url ,:approved ,:status

  has_many :properties, :dependent => :destroy

  #scope :status, where(status: true)

  has_many :contacts


  # attr_accessible :title, :body

  validates :phone, :numericality => { :only_integer => true }, :length => {:minimum => 10, :maximum => 10}
  #validates_format_of :first_name, :with => /\A[[:graph:]]\Z/i
  has_attached_file :logo
  before_create :approve_user?
  
  def approve_user?
    self.approved = true
  end
  
  def active_for_authentication? 
    super && approved? 
  end 

  validates_format_of :first_name,:last_name,:company_name ,:address, :city,:with => /\A[^\d]+\Z/, :message => "field should only have letters"
  validates_format_of :company_url, :with => URI::regexp(%w(http https)), :message=>"is like this http://www.companyname.com"

  
 
  validate :email_exists
  
   def email_exists
    if User.exists?(:email => self.email)
      errors.add(:email,"User already exists with this email, try another email")
    end
  end 
  
end

app/controllers/admin/builders_controller.rb
class Admin::BuildersController < ApplicationController
  layout :layout
  
  def layout
    'admin'
  end
  
  def index
    @builders=Builder.all
  end
   
  def block_builders
    @builders=Builder.find(params[:id])
    if params[:status] == 'tru'
      @builders.update_attribute(:approved,true)
    else
      @builders.update_attribute(:approved,false)
    end
    redirect_to '/admin/builders/'
  end
    
  def manage_properties
    @builder = Builder.find_by_id(params[:id])
    @properties = @builder.properties
  end
    
end

app/helpers/admin/builders_helper.rb
module Admin::BuildersHelper
end

app/views/admin/builders/index.html.erb
<div align="center">
  <table border="2">
    <tr>
      <th>Id</th>
      <th>Company Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>City</th>
      <th>Property Listing</th>
      <th>Last sign_in</th>
      <th>Action</th>
      <th>Add Property</th>
    </tr>
    <% @builders.each do |builder| %>
      <tr>
        <td align="center"><%=builder.id%></td>
        <td align="center"><%=builder.company_name%>
        <td align="center"><%= builder.email%></td>
        <td align="center"><%=builder.phone%></td>
        <td align="center"><%=builder.city%></td>
        <td align="center"><%= link_to "#{builder.properties.count}", manage_properties_admin_builder_path(builder) %></td>

        <td align="center"><%=builder. last_sign_in_at %></td>
        <td align="center">
          <%=  builder.approved == false ? (link_to image_tag('cross.png'), block_builders_admin_builder_path(builder, :status => 'tru')) : (link_to image_tag('r.gif'), block_builders_admin_builder_path(builder, :status => 'fal'))%>
        </td>
        <td align="center">
          <%= link_to image_tag('ap.jpg'),new_builder_property_path(builder) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/builders/manage_properties.html.erb
<table class="table table-striped" cellspacing="10" cellpadding="10" border="1">
  <tr>
    <th>PropertyName</th>
    <th>PropertyListing</th>
    <th>PropertyType</th>
    <th>TotalArea</th>
    <th>SalePrice</th>
    <th>State</th>
    <th>City</th>
    <th>Address</th>
    <th>PropertyStatus</th>
    <th>StartDate</th>
    <th>EndDate</th>
    <th>UpcomingDate</th>
    <th>Action</th>
  </tr>

  <% @properties.each do |property| %>
    <tr>
      <td align="center">
        <%= property.property_name %>
      </td>
      <td align="center">
        <%= property.property_listing %>
      </td>
      <td align="center">
        <%= property.property_type %>
      </td>
      <td align="center">
        <%= property.total_area %>
      </td>
      <td align="center">
        <%= property.sale_price %>
      </td>
      <td align="center">
        <%= property.state %>
      </td>
      <td align="center">
        <%= property.city %>
      </td>
      <td align="center">
        <%= property.address %>
      </td>
      <td align="center">
        <%= property.property_status %>
      </td>
      <td>  
        <% if property.property_status == "Ongoing"  %>

          <%=property.start_date %>

        <td>
          <%=property.end_date %>
        </td>

      <% end %>

      <% if property.property_status == "Ready To Move"  %>
        <td>
          <%=property.end_date %>
        </td>
      <% end %>


      <td> 
        <% if property.property_status == "Upcoming"  %>
        <td>
          <%=property.upcoming_date %>
        </td>
      <% end %>
      </td>
      </td>

      <td>
        <%= link_to property.published == false ? image_tag('cross.png') : image_tag('r.gif'), manage_property_builder_property_path(:builder_id => property.builder_id,:id =>property.id,:status => property.published == false ? true : false)%></br>
        <%= link_to image_tag('vp.jpg'),  builder_property_path(property.builder_id,property) %>
        <%= link_to image_tag('sum.jpg'), summary_builder_property_path(property.builder_id,property) %>
      </td>
    </tr>
  <% end %>
</table>