config/routes.rb
Realestate::Application.routes.draw do
  
  devise_for :admins

  devise_for :builders
 

  resources :dashboards do
    collection do
      get 'search'
    end
  end
 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :builderregistrations
  resources :profiles 
  
    
   
  namespace :admin do
    resources :users
    resources :builders do
      member do
        get :block_builders
        get :manage_properties
      end
    end
  end

  devise_scope :user do
    get "sign_out", :to => "sessions#destroy"
  end
  
  

  resources :images
  
  resources :builders do
    resources :properties do
      member do
        get :manage_property
        get 'summary'
      end
    end
  end
  
  resources :properties do
  member do
    get 'add_contact'
    post 'post_contact'
    get 'reply_user'
  end
end
  
  
  
  

root :to => 'dashboards#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    if current_builder
      @builder = current_builder 
    elsif current_admin
      render :layout => 'admin'
    end
  end
  
  def search        
    @properties = Property.property_listing(params[:property_listing]).property_type(params[:property_type]).sale_price(params[:sale_price]).city(params[:city]).paginate(:page => params[:page], :per_page => 5)
    @properties.each do|property|
    property.update_attributes(:search_view => property.search_view + 1)
    end
    @json = @properties.to_gmaps4rails
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @property = Property.find(params[:id])
    @json = @property.to_gmaps4rails
  end
 
 end

  
  #    query=[]
#    query << "#{params[:property_listing]}" if(params[:property_listing]).present?
#    query << "#{params[:property_type]}" if(params[:property_type]).present?
#    query << "#{params[:city]}" if(params[:city]).present?
#    query << "#{params[:sale_price]}" if(params[:sale_price]).present?
   # @properties = Property.search("*#{query}*", :page=>params[:page], :per_page=>5)   

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<% if !current_builder %>
<h3>
  Search For Real Estate
</h3>
<%= form_tag search_dashboards_path, :method => 'get', :class => 'form_search' do |f| %>
<div>
  <div style="float: left;">
    <%= select_tag :property_listing, options_for_select([["Buy","For Sale"], ["Rent","For Rent"], ["Buy / Rent","For Sale or Rent"]]) %>
    <%= select_tag :property_type, options_for_select([["Select",""], ["Apartment","Apartment"], ["Villa","Villa"], ["Row House","Row House"], ["Layout","Layout"]]) %>  
  </div> 

  <div style="float: left;">
    <%= text_field_tag :city, nil, :placeholder => 'Enter City Name', :class => 'input-medium search-query' %>
    <%= text_field_tag :sale_price, nil, :placeholder => 'Enter Price Value', :class => 'input-medium search-query' %>
  </div>
  
  <div style="float: left;">
    <%= submit_tag  "Search Property", :class => 'btn btn-primary' %>
  </div>  
</div>  
<% end %>
<% end %>

app/views/dashboards/index.html.erb
<% if !current_admin %>
  <div id="search">
    <%= render :partial => 'form' %>
  </div>
<% end %>

app/views/dashboards/search.html.erb
<div class="row">
  <div class="span9 offset2"><%= gmaps4rails(@json) %></div>
</div>

<br/>
<div class="row">
  <% if @properties.present? %>
    <% @properties.each do |property| %>
      <div class="span3">
        <div class="row">
          <div class="span3"><%= property.property_name %></div>
          <% property.images.each do |image| %>
            <%= image_tag(image.image, :height => '200px', :width => '200px;', :class=>"img-polaroid") %>
          <% end %>
          <div class="span3"><%= property.property_type %></div>
          <div class="span3">City: <%=property.city %></div>
          <div class="span3"><%= property.property_listing %><br/></div>
          <div class="span3">Sale Area: <%=property.saleable_area + "sq.ft" %></div>
          <div class="span3">Sale Price: Rs. <%= property.sale_price %></div>
          <div class="span3">Status:<%=property.property_status%></div>
          <div class="span3">
            <%= link_to 'Full Details', property_path(property), :class => "btn btn-small btn-primary" %> &nbsp; 
            <%= link_to "View Map", dashboard_path(property), :class => "btn btn-small btn-primary" %>
          </div>
        </div>
      </div>
    <%end%>
  <% end %>
</div>

<div class="pagination pagination-centered pagination-large">
  <%= will_paginate(@properties) %>
</div>

app/views/dashboards/show.html.erb
<%= render :partial => 'properties/map' %>